# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

GCC_BIN = 
PROJECT = IAsservPetitRobot2012
OBJECTS = ./IA/ProcTelemetres/ProcTelemetres.o ./IA/Telemetre/Telemetre.o ./IA/IA/IA.o ./asserv/odometrie/Odometrie.o ./asserv/consignController/ConsignController.o ./asserv/filtres/QuadRampDerivee/QuadRampDerivee.o ./asserv/filtres/Pid/Pid.o ./asserv/regulateur/Regulateur.o ./asserv/commandManager/CommandManager.o ./asserv/commandManager/CMDList/CMDList.o ./asserv/motorsController/Md22/Md22.o ./asserv/motorsController/PololuSMCs/PololuSMCs.o ./asserv/motorsController/PololuSMCs/OnePololuSMC.o ./asserv/motorsController/Qik/Qik.o ./asserv/debug/DebugUDP.o ./asserv/Utils/Utils.o ./asserv/codeurs/Codeur.o ./asserv/codeurs/CodeursDirects.o ./asserv/codeurs/CodeursAVR.o ./asserv/main/Main.o 
SYS_OBJECTS = ./mbed/LPC1768/cmsis_nvic.o ./mbed/LPC1768/system_LPC17xx.o ./mbed/LPC1768/core_cm3.o ./mbed/LPC1768/stackheap.o ./mbed/LPC1768/startup_LPC17xx.o 
INCLUDE_PATHS = -I. -I./EthernetNetIf -I./EthernetNetIf/LPC1768 -I./EthernetNetIf/LPC1768/drv -I./EthernetNetIf/LPC1768/drv/eth -I./EthernetNetIf/LPC1768/lwip -I./EthernetNetIf/LPC1768/lwip/netif -I./EthernetNetIf/LPC1768/lwip/netif/ppp -I./EthernetNetIf/LPC1768/lwip/include -I./EthernetNetIf/LPC1768/lwip/include/netif -I./EthernetNetIf/LPC1768/lwip/include/lwip -I./EthernetNetIf/LPC1768/lwip/include/ipv4 -I./EthernetNetIf/LPC1768/lwip/include/ipv4/lwip -I./EthernetNetIf/LPC1768/lwip/arch -I./EthernetNetIf/LPC1768/api -I./EthernetNetIf/LPC1768/dbg -I./EthernetNetIf/LPC1768/if -I./EthernetNetIf/LPC1768/if/lwip -I./EthernetNetIf/LPC1768/if/eth -I./EthernetNetIf/LPC1768/if/net -I./EthernetNetIf/LPC1768/core -I./mbed -I./mbed/LPC1768 -I./IA -I./IA/ProcTelemetres -I./IA/Telemetre -I./IA/IA -I./asserv -I./asserv/odometrie -I./asserv/consignController -I./asserv/filtres -I./asserv/filtres/QuadRampDerivee -I./asserv/filtres/Pid -I./asserv/regulateur -I./asserv/commandManager -I./asserv/commandManager/CMDList -I./asserv/motorsController -I./asserv/motorsController/Md22 -I./asserv/motorsController/PololuSMCs -I./asserv/motorsController/Qik -I./asserv/debug -I./asserv/Utils -I./asserv/codeurs -I./asserv/main 
LIBRARY_PATHS = 
LIBRARIES = 
LINKER_SCRIPT = None

############################################################################### 
CC = $(GCC_BIN)arm-none-eabi-gcc
CPP = $(GCC_BIN)arm-none-eabi-g++
CC_FLAGS = -c -Os -fno-common -fmessage-length=0 -Wall -fno-exceptions -mcpu=cortex-m3 -mthumb -ffunction-sections -fdata-sections 
ONLY_C_FLAGS = -std=gnu99
ONLY_CPP_FLAGS = -std=gnu++98
CC_SYMBOLS = -DTARGET_LPC1768 -DTOOLCHAIN_GCC_ARM -DNDEBUG -D__CORTEX_M3


AS = $(GCC_BIN)arm-none-eabi-as

LD = $(GCC_BIN)arm-none-eabi-gcc
LD_FLAGS = -mcpu=cortex-m3 -mthumb -Wl,--gc-sections
LD_SYS_LIBS = -lstdc++ -lsupc++ -lm -lc -lgcc

OBJCOPY = $(GCC_BIN)arm-none-eabi-objcopy

all: $(PROJECT).bin

clean:
	rm -f $(PROJECT).bin $(PROJECT).elf $(OBJECTS)

.s.o:
	$(AS) -o $@ $<

.c.o:
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) $(ONLY_C_FLAGS)   $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	$(CPP) $(CC_FLAGS) $(CC_SYMBOLS) $(ONLY_CPP_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS)
	$(LD) $(LD_FLAGS) -T$(LINKER_SCRIPT) $(LIBRARY_PATHS) -o $@ $^ $(LIBRARIES) $(LD_SYS_LIBS) $(LIBRARIES) $(LD_SYS_LIBS)

$(PROJECT).bin: $(PROJECT).elf
	$(OBJCOPY) -O binary $< $@
